echo Creating new keystore for release...
keytool -genkey -v -keystore noussousse-release-key.keystore -alias noussousse -keyalg RSA -keysize 2048 -validity 10000 -storepass MySecurePassword123 -keypass MySecurePassword123 -dname "CN=AppLov, OU=Development, O=AppLov, L=City, ST=State, C=US"
